services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: admin
      DB_PASSWORD: Taszka16
      DB_DATABASE: defaultdb
      DB_SYNCHRONIZE: "true"
      DB_LOGGING: "true"
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: Taszka16
      JWT_SECRET: 8248507a4e96a007d5c0502e2f29a0aea89e5d73e7612ea518cfc1939b38026a
      JWT_EXPIRES_IN: 3600s
      PORT: 8080
      NODE_ENV: production
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: defaultdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: Taszka16
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_data:
