services:
  - type: web
    name: practica-backend
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api
    envVars:
      - key: DB_HOST
        value: mysql-299c61dd-leyplay14-6cb9.f.aivencloud.com
      - key: DB_PORT
        value: "23662"
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_SYNCHRONIZE
        value: "true"
      - key: DB_SSL_CA_PATH
        value: ca-cert.pem
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 3600s
      - key: NODE_ENV
        value: production
